#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 21 16:53:59 2021

@author: mollysandler
"""

class Order:
    def __init__(self, ctype, milk, size, price):
        self.ctype = ctype
        self.milk = milk
        self.size = size
        self.price = price
        