#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov  2 15:18:03 2021

@author: mollysandler
"""

import unittest

from new import calculate_average

class testAverage(unittest.TestCase):
    
    def test_calc_average_zeros(self):
       studentGrade = [0, 0, 0, 0, 0]
       self.assertEqual(calculate_average(studentGrade), 0 , "something went wrong")
       
    def test_calc_average_repeat(self):
       studentGrade = [100, 20, 4, 100, 1000]
       self.assertEqual(calculate_average(studentGrade), 244.8, "something went wrong")
       
    def test_calc_average_negatives(self):
       studentGrade = [-7, -60, 50, 12, 15]
       self.assertEqual(calculate_average(studentGrade), 2 , "something went wrong")
       

if __name__ == "__main__":
    unittest.main()  