#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  4 12:56:29 2021

@author: mollysandler
"""

user = ["kayak" ,"zebra" ,"civic" , "apart" ,"madam" ,"stops "]

def is_palindrome(listing):
    newlist= [item for item in listing if item[0]==item[4] and item[1] == item[3] in item]    
    print (newlist)
    return newlist
    
        

