#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 21 17:12:00 2021

@author: mollysandler
"""

import sys

ctype = input('plesae enter the type of coffee you want: ')
milk= input("Would you like milk with that? ")
size = input('please enter the size you want: ')

def error():
    print('Sorry we cannot help you here')
    sys.exit

 

def getType(ctype):
    if ctype.lower() == "latte" or ctype.lower() == "iced latte" or ctype.lower() == "black" or ctype.lower() == "iced black":
        print ("Great, thank you")
    elif ctype.lower() != "latte" and ctype.lower() != "iced latte" and ctype.lower() != "black" and ctype.lower() != "iced black":
        print ("Sorry! Invalid Input, try again")
        ctype = input('plesae enter the type of coffee you want: ')
        if ctype.lower() != "latte" and ctype.lower() != "iced latte" and ctype.lower() != "black" and ctype.lower() != "iced black":
            print ("Sorry! Invalid Input, try again")
            ctype = input('plesae enter the type of coffee you want: ')
            if ctype.lower() != "latte" and ctype.lower() != "iced latte" and ctype.lower() != "black" and ctype.lower() != "iced black":
                error()
    return ctype

def getMilk(milk):
    if ctype.lower() == "black" or ctype == "iced black" :
        
        if milk.lower() == "y" or milk.lower() == "n":
            print ("Great, thank you")
        elif milk.lower() != "y" and milk.lower() != "n" :
            print ("Sorry! Invalid input, try again")
            milk = input("Would you like milk with that? ")
            if milk.lower() != "y" and milk.lower() != "n" :
                print ("Sorry! Invalid input, try again")
                milk = input("Would you like milk with that? ")
                if milk.lower() != "y" and milk.lower() != "n" :
                    error()
        return milk

def getSize(size):
    if size.lower() == "short" or size.lower() == "regular" or size.lower() == 'large':
        print ("Great, thank you")
    elif size.lower() != "short" and size.lower() != "regular" and size.lower() != "large":
        print ("Sorry! Invalid Input, try again")
        size = input('please enter the size you want: ')
        if ctype.lower() != "latte" and size.lower() != "iced latte" and size.lower() != "large":
            print ("Sorry! Invalid Input, try again")
            size = input('please enter the size you want: ')
            if size.lower() != "latte" and size.lower() != "iced latte" and size.lower() != "large":
                error()
    return size
        
def getPrice():
    
    if ctype.lower() == "black":
        if size.lower() == "short":
            if milk.lower() == "y":
                price = "1.30"
            elif milk.lower() == "n":
                price = "1.25"
        elif size.lower() == "regular":
            if milk.lower() == "y":
                price = "1.60"
            elif milk.lower() == "n":
                price = "1.50"
        elif size == "Large":
            if milk.lower() == "y":
                price = "1.95"
            elif milk.lower() == "n":
                price = "1.75"
    elif ctype.lower() == "iced black":
        if size.lower() == "short":
            if milk.lower() == "y":
                price = "1.45"
            elif milk.lower() == "n":
                price = "1.40"
        elif size.lower() == "regular":
            if milk.lower() == "y":
                price = "2.00"
            elif milk.lower() == "n":
                price = "1.90"
        elif size.lower() == "large":
            if milk.lower() == "y":
                price = "2.60"
            elif milk.lower() == "n":
                price = "2.40"
    elif ctype.lower() == "latte":
        if size.lower() == "short":
            price = "2.00"
        elif size.lower() == "regular":
            price = "2.50"
        elif size.lower() == "large":
            price = "3.00"
    elif ctype.lower() == "iced latte":
        if size.lower() == "Short":
            price = "2.20"
        elif size.lower() == "regular":
            price = "2.70"
        elif size.lower() == "large":
            price = "3.20"
    return price 


        
getType(ctype)
getMilk(milk)
getSize(size)



#Python3 program to show that we can create 
# instance variables inside methods
    
# Class for Dog
class Dog:
       
    # Class Variable
    animal = 'dog'     
       
    # The init method or constructor
    def __init__(self, breed):
           
        # Instance Variable
        self.breed = breed            
   
    # Adds an instance variable 
    def setColor(self, color):
        self.color = color
       
    # Retrieves instance variable    
    def getColor(self):    
        return self.color   
   
# Driver Code
Rodger = Dog("pug")
Rodger.setColor("brown")
print(Rodger.getColor()) 
 



