#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  1 22:45:30 2021

@author: mollysandler
"""    
    
import unittest

from untitled13 import *

class Testdistance(unittest.TestCase):
    
    def test_inside_circle(self):
        Point1 = Point(3,4)
        Circle1 = Circle(0, 0, 6)
        print(point_location(Point1, Circle1))
        
        self.assertEqual(point_location(Point1, Circle1), "Inside Circle" , "Should say Inside Circle")
        
    def test_outside_circle(self):
        Point2 = Point(3,4)
        Circle2 = Circle(0, 0, 2)
        
        self.assertEqual(point_location(Point2, Circle2), "Outside Circle", "Should say Outside Circle")
        
    def test_on_circle(self):
        Point3 = Point(3,4)
        Circle3 = Circle(0, 0, 5)
        
        self.assertEqual(point_location(Point3, Circle3), "On Circle" , "Should say On Circle")
        
if __name__ == "__main__":
    unittest.main()  
    
    