#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 26 13:47:46 2021

@author: mollysandler
"""
    
    
import unittest 

from untitled9 import add

class test_add(unittest.TestCase): 
    def test_add_positive(self):
        self.assertEqual(add(3,4), 7, "should be 7")
    def test_add_negative(self):
        self.assertEqual(add(-3,-4), -7, "should be -7")
        
from untitled9 import subtract

class test_subtract(unittest.TestCase): 
    def test_sub_positive(self):
        self.assertEqual(subtract(3,4), -1, "should be -1")
    def test_sub_negative(self):
        self.assertEqual(subtract(-3,-4), 1, "should be 1")

from untitled9 import multiply

class test_multiply(unittest.TestCase): 
    def test_multiply_positive(self):
        self.assertEqual(multiply(3,4), 12, "should be 12")
    def test_multiply_negative(self):
        self.assertEqual(multiply(-3,-5), 15, "should be 15")

from untitled9 import divide

class test_divide(unittest.TestCase): 
    def test_divide_fraction(self):
        self.assertEqual(divide(2,1), 2, "should be 1/3")
    def test_divide_negative(self):
        self.assertEqual(divide(-20,-2), 10, "should be 10")        
if __name__ == "__main__":
    unittest.main()   