#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 20 22:31:10 2021

@author: mollysandler
"""

import unittest
from untitled4 import add
from untitled4 import subtract
from untitled4 import multiply
from untitled4 import divide


class additionTest(unittest.TestCase):
    def addition():
        assert add(2,3) == 5
    


additionTest()