#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov  2 15:25:30 2021

@author: mollysandler
"""
import math

#task one
'''studentGrade = [60, 12, 34, 56, 78]

def calculate_average(grades):
    i = 0
    sum = 0
    while (i < len(grades)):
        sum = sum + grades[i]
        i = i + 1
        average = sum/len(grades)
        grades.sort()
        print(grades)
        print(average)
        return average


calculate_average(studentGrade)

#task two 
from palindrome import is_palindrome

words = ["kayak" ,"zebra" ,"civic" , "apart" ,"madam" ,"stops "]

def filter_palindromes(listings):
   newList = [item for item in words if is_palindrome(words) in words]
   return newList

    
filter_palindromes(words)'''



#task 3
num = int(input('please enter a number: '))
def exponent(number):
    new = math.exp(number)
    return new
    
exponent(num)
